from enum import Enum

class ContextEventType(str, Enum):
    APPLICATION_OPENED = "APPLICATION_OPENED"
    APPLICATION_CLOSED = "APPLICATION_CLOSED"
    WINDOW_FOCUSED = "WINDOW_FOCUSED"
    SEARCH_PERFORMED = "SEARCH_PERFORMED"
    URL_OPENED = "URL_OPENED"
    VOLUME_CHANGED = "VOLUME_CHANGED"
    SCREEN_ACTION = "SCREEN_ACTION"
    COMMAND_FAILED = "COMMAND_FAILED"
