from enum import Enum

class WindowError(str, Enum):
    WINDOW_NOT_FOUND = "WINDOW_NOT_FOUND"
    WINDOW_DESTROYED = "WINDOW_DESTROYED"
    ACCESS_DENIED = "ACCESS_DENIED"
    FOREGROUND_RESTRICTED = "FOREGROUND_RESTRICTED"
    WINDOW_CLOAKED = "WINDOW_CLOAKED"
    MULTIPLE_MATCHES = "MULTIPLE_MATCHES"
    WINDOW_ALREADY_FOCUSED = "WINDOW_ALREADY_FOCUSED"
    WINDOW_ALREADY_CLOSED = "WINDOW_ALREADY_CLOSED"
